#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum AddressingMode {
    Unknown,
    Implied,
    Immediate,
    Indirect,
    Relative,
    Accumulator,
    ZeroPage,
    ZeroPageX,
    ZeroPageY,
    Absolute,
    AbsoluteX,
    AbsoluteY,
    IndirectX,
    IndirectY,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct OpCode {
    pub code: u8,
    pub mnemonic: &'static str,
    pub length: u8,
    pub time: u8,
    pub mode: AddressingMode,
}

impl OpCode {
    pub fn from_raw_byte(byte: u8) -> OpCode {
        OpCodes.iter().find(|opcode| opcode.code == byte).expect("Invalid opcode").clone()
    }

    pub fn from_mnemonic<S>(input: S) -> Option<OpCode>
        where S: Into<String>
    {
        let input = input.into();
        OpCodes.iter()
            .find(|opcode| opcode.mnemonic == input.to_uppercase())
            .cloned()
    }

    pub fn from_mnemonic_and_addressing_mode<S>(input: S, mode: AddressingMode) -> Option<OpCode>
        where S: Into<String>
    {
        let input = input.into();
        OpCodes.iter()
            .find(|opcode| opcode.mnemonic == input.to_uppercase() && opcode.mode == mode)
            .cloned()
    }
}

// List of OpCodes. Source: http://www.6502.org/tutorials/6502opcodes.html#ADC
static OpCodes: [OpCode; 151] = [OpCode {
                                     code: 0x69,
                                     mnemonic: "ADC",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0x65,
                                     mnemonic: "ADC",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x75,
                                     mnemonic: "ADC",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x6D,
                                     mnemonic: "ADC",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x7D,
                                     mnemonic: "ADC",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x79,
                                     mnemonic: "ADC",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0x61,
                                     mnemonic: "ADC",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectX,
                                 },
                                 OpCode {
                                     code: 0x71,
                                     mnemonic: "ADC",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::IndirectY,
                                 },
                                 OpCode {
                                     code: 0x29,
                                     mnemonic: "AND",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0x25,
                                     mnemonic: "AND",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x35,
                                     mnemonic: "AND",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x2D,
                                     mnemonic: "AND",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x3D,
                                     mnemonic: "AND",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x39,
                                     mnemonic: "AND",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0x21,
                                     mnemonic: "AND",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectX,
                                 },
                                 OpCode {
                                     code: 0x31,
                                     mnemonic: "AND",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::IndirectY,
                                 },
                                 OpCode {
                                     code: 0x0A,
                                     mnemonic: "ASL",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Accumulator,
                                 },
                                 OpCode {
                                     code: 0x06,
                                     mnemonic: "ASL",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x16,
                                     mnemonic: "ASL",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x0E,
                                     mnemonic: "ASL",
                                     length: 3,
                                     time: 6,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x1E,
                                     mnemonic: "ASL",
                                     length: 3,
                                     time: 7,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x24,
                                     mnemonic: "BIT",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x2C,
                                     mnemonic: "BIT",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x10,
                                     mnemonic: "BPL",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Relative,
                                 },
                                 OpCode {
                                     code: 0x30,
                                     mnemonic: "BMI",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Relative,
                                 },
                                 OpCode {
                                     code: 0x50,
                                     mnemonic: "BVC",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Relative,
                                 },
                                 OpCode {
                                     code: 0x70,
                                     mnemonic: "BVS",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Relative,
                                 },
                                 OpCode {
                                     code: 0x90,
                                     mnemonic: "BCC",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Relative,
                                 },
                                 OpCode {
                                     code: 0xB0,
                                     mnemonic: "BCS",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Relative,
                                 },
                                 OpCode {
                                     code: 0xD0,
                                     mnemonic: "BNE",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Relative,
                                 },
                                 OpCode {
                                     code: 0xF0,
                                     mnemonic: "BEQ",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Relative,
                                 },
                                 OpCode {
                                     code: 0x00,
                                     mnemonic: "BRK",
                                     length: 1,
                                     time: 7,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xC9,
                                     mnemonic: "CMP",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0xC5,
                                     mnemonic: "CMP",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xD5,
                                     mnemonic: "CMP",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0xCD,
                                     mnemonic: "CMP",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xDD,
                                     mnemonic: "CMP",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0xD9,
                                     mnemonic: "CMP",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0xC1,
                                     mnemonic: "CMP",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectX,
                                 },
                                 OpCode {
                                     code: 0xD1,
                                     mnemonic: "CMP",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::IndirectY,
                                 },
                                 OpCode {
                                     code: 0xE0,
                                     mnemonic: "CPX",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0xE4,
                                     mnemonic: "CPX",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xEC,
                                     mnemonic: "CPX",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xC0,
                                     mnemonic: "CPY",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0xC4,
                                     mnemonic: "CPY",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xCC,
                                     mnemonic: "CPY",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xC6,
                                     mnemonic: "DEC",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xD6,
                                     mnemonic: "DEC",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0xCE,
                                     mnemonic: "DEC",
                                     length: 3,
                                     time: 6,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xDE,
                                     mnemonic: "DEC",
                                     length: 3,
                                     time: 7,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x49,
                                     mnemonic: "EOR",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0x45,
                                     mnemonic: "EOR",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x55,
                                     mnemonic: "EOR",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x4D,
                                     mnemonic: "EOR",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x5D,
                                     mnemonic: "EOR",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x59,
                                     mnemonic: "EOR",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0x41,
                                     mnemonic: "EOR",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectX,
                                 },
                                 OpCode {
                                     code: 0x51,
                                     mnemonic: "EOR",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::IndirectY,
                                 },
                                 OpCode {
                                     code: 0x18,
                                     mnemonic: "CLC",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x38,
                                     mnemonic: "SEC",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x58,
                                     mnemonic: "CLI",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x78,
                                     mnemonic: "SEI",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xB8,
                                     mnemonic: "CLV",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xD8,
                                     mnemonic: "CLD",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xF8,
                                     mnemonic: "SED",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xE6,
                                     mnemonic: "INC",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xF6,
                                     mnemonic: "INC",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0xEE,
                                     mnemonic: "INC",
                                     length: 3,
                                     time: 6,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xFE,
                                     mnemonic: "INC",
                                     length: 3,
                                     time: 7,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x4C,
                                     mnemonic: "JMP",
                                     length: 3,
                                     time: 3,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x6C,
                                     mnemonic: "JMP",
                                     length: 3,
                                     time: 5,
                                     mode: AddressingMode::Indirect,
                                 },
                                 OpCode {
                                     code: 0x20,
                                     mnemonic: "JSR",
                                     length: 3,
                                     time: 6,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xA9,
                                     mnemonic: "LDA",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0xA5,
                                     mnemonic: "LDA",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xB5,
                                     mnemonic: "LDA",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0xAD,
                                     mnemonic: "LDA",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xBD,
                                     mnemonic: "LDA",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0xB9,
                                     mnemonic: "LDA",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0xA1,
                                     mnemonic: "LDA",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectX,
                                 },
                                 OpCode {
                                     code: 0xB1,
                                     mnemonic: "LDA",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::IndirectY,
                                 },
                                 OpCode {
                                     code: 0xA2,
                                     mnemonic: "LDX",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0xA6,
                                     mnemonic: "LDX",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xB6,
                                     mnemonic: "LDX",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageY,
                                 },
                                 OpCode {
                                     code: 0xAE,
                                     mnemonic: "LDX",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xBE,
                                     mnemonic: "LDX",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0xA0,
                                     mnemonic: "LDY",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0xA4,
                                     mnemonic: "LDY",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xB4,
                                     mnemonic: "LDY",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0xAC,
                                     mnemonic: "LDY",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xBC,
                                     mnemonic: "LDY",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x4A,
                                     mnemonic: "LSR",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Accumulator,
                                 },
                                 OpCode {
                                     code: 0x46,
                                     mnemonic: "LSR",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x56,
                                     mnemonic: "LSR",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x4E,
                                     mnemonic: "LSR",
                                     length: 3,
                                     time: 6,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x5E,
                                     mnemonic: "LSR",
                                     length: 3,
                                     time: 7,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0xEA,
                                     mnemonic: "NOP",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x09,
                                     mnemonic: "ORA",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0x05,
                                     mnemonic: "ORA",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x15,
                                     mnemonic: "ORA",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x0D,
                                     mnemonic: "ORA",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x1D,
                                     mnemonic: "ORA",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x19,
                                     mnemonic: "ORA",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0x01,
                                     mnemonic: "ORA",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectX,
                                 },
                                 OpCode {
                                     code: 0x11,
                                     mnemonic: "ORA",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::IndirectY,
                                 },
                                 OpCode {
                                     code: 0xAA,
                                     mnemonic: "TAX",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x8A,
                                     mnemonic: "TXA",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xCA,
                                     mnemonic: "DEX",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xE8,
                                     mnemonic: "INX",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xA8,
                                     mnemonic: "TAY",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x98,
                                     mnemonic: "TYA",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x88,
                                     mnemonic: "DEY",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xC8,
                                     mnemonic: "INY",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x2A,
                                     mnemonic: "ROL",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Accumulator,
                                 },
                                 OpCode {
                                     code: 0x26,
                                     mnemonic: "ROL",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x36,
                                     mnemonic: "ROL",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x2E,
                                     mnemonic: "ROL",
                                     length: 3,
                                     time: 6,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x3E,
                                     mnemonic: "ROL",
                                     length: 3,
                                     time: 7,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x6A,
                                     mnemonic: "ROR",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Accumulator,
                                 },
                                 OpCode {
                                     code: 0x66,
                                     mnemonic: "ROR",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x76,
                                     mnemonic: "ROR",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x6E,
                                     mnemonic: "ROR",
                                     length: 3,
                                     time: 6,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x7E,
                                     mnemonic: "ROR",
                                     length: 3,
                                     time: 7,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x40,
                                     mnemonic: "RTI",
                                     length: 1,
                                     time: 6,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x60,
                                     mnemonic: "RTS",
                                     length: 1,
                                     time: 6,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xE9,
                                     mnemonic: "SBC",
                                     length: 2,
                                     time: 2,
                                     mode: AddressingMode::Immediate,
                                 },
                                 OpCode {
                                     code: 0xE5,
                                     mnemonic: "SBC",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0xF5,
                                     mnemonic: "SBC",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0xED,
                                     mnemonic: "SBC",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0xFD,
                                     mnemonic: "SBC",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0xF9,
                                     mnemonic: "SBC",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0xE1,
                                     mnemonic: "SBC",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectX,
                                 },
                                 OpCode {
                                     code: 0xF1,
                                     mnemonic: "SBC",
                                     length: 2,
                                     time: 5,
                                     mode: AddressingMode::IndirectY,
                                 },
                                 OpCode {
                                     code: 0x85,
                                     mnemonic: "STA",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x95,
                                     mnemonic: "STA",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x8D,
                                     mnemonic: "STA",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x9D,
                                     mnemonic: "STA",
                                     length: 3,
                                     time: 5,
                                     mode: AddressingMode::AbsoluteX,
                                 },
                                 OpCode {
                                     code: 0x99,
                                     mnemonic: "STA",
                                     length: 3,
                                     time: 5,
                                     mode: AddressingMode::AbsoluteY,
                                 },
                                 OpCode {
                                     code: 0x81,
                                     mnemonic: "STA",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectX,
                                 },
                                 OpCode {
                                     code: 0x91,
                                     mnemonic: "STA",
                                     length: 2,
                                     time: 6,
                                     mode: AddressingMode::IndirectY,
                                 },
                                 OpCode {
                                     code: 0x9A,
                                     mnemonic: "TXS",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0xBA,
                                     mnemonic: "TSX",
                                     length: 1,
                                     time: 2,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x48,
                                     mnemonic: "PHA",
                                     length: 1,
                                     time: 3,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x68,
                                     mnemonic: "PLA",
                                     length: 1,
                                     time: 4,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x08,
                                     mnemonic: "PHP",
                                     length: 1,
                                     time: 3,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x28,
                                     mnemonic: "PLP",
                                     length: 1,
                                     time: 4,
                                     mode: AddressingMode::Implied,
                                 },
                                 OpCode {
                                     code: 0x86,
                                     mnemonic: "STX",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x96,
                                     mnemonic: "STX",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageY,
                                 },
                                 OpCode {
                                     code: 0x8E,
                                     mnemonic: "STX",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 },
                                 OpCode {
                                     code: 0x84,
                                     mnemonic: "STY",
                                     length: 2,
                                     time: 3,
                                     mode: AddressingMode::ZeroPage,
                                 },
                                 OpCode {
                                     code: 0x94,
                                     mnemonic: "STY",
                                     length: 2,
                                     time: 4,
                                     mode: AddressingMode::ZeroPageX,
                                 },
                                 OpCode {
                                     code: 0x8C,
                                     mnemonic: "STY",
                                     length: 3,
                                     time: 4,
                                     mode: AddressingMode::Absolute,
                                 }];
